packages:
  - apps/*
  - packages/*

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  unrs-resolver: true

packageExtensions:
  '@sentry/react-native@*':
    dependencies:
      '@expo/config-plugins': '^55.0.10'
